GEOGRAPHY, AGE_GROUP, COHORT_SIZE, CHURNED_COUNT, CHURN_RATE_PCT, AVG_TENURE, CHURN_0_2YR_PCT, CHURN_0_5YR_PCT, CHURN_0_10YR_PCT-- STEP 1: Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS CHURN_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Churn Analytics Warehouse';

-- STEP 2: Create Database
CREATE DATABASE IF NOT EXISTS CHURN_ANALYTICS;

-- STEP 3: Create Schema
CREATE SCHEMA IF NOT EXISTS CHURN_ANALYTICS.ANALYTICS;

-- STEP 4: Set context
USE WAREHOUSE CHURN_WH;
USE DATABASE CHURN_ANALYTICS;
USE SCHEMA ANALYTICS;

-- STEP 5: Verify
SHOW WAREHOUSES;
SHOW DATABASES;